services:
  blazorapp1:
    image: blazorapp1
    build:
      context: .
      dockerfile: BlazorApp1/Dockerfile

  runningplanner.site:
    image: runningplanner.site
    build:
      context: .
      dockerfile: RunningPlanner.Site/Dockerfile

  runningplanner.core:
    image: runningplanner.core
    build:
      context: .
      dockerfile: RunningPlanner.Core/Dockerfile
